### ISSUE TITLE
[CRDOM203] [Html] HTML page must contain a doctype tag

### ISSUE THREAD

**Issue by Chmaqo** [green-code-initiative/ecoCode#103]
Team 5R

**Comment by utarwyn** [comment]
Hello! I think that this rule is more related to HTML than PHP, no?
Maybe we could integrate it in the future HTML linter discussed in green-code-initiative/ecoCode-linter#4, if a warning is not already reported (because I think a document is not valid if DOCTYPE is not set, [check doc here](https://www.w3.org/wiki/Doctypes_and_markup_styles))

**Comment by MP-Aubay** [comment]
Does this issue is covered by this existing sonar rule : https://rules.sonarsource.com/html/RSPEC-1095 ?

**Comment by Silicoman** [comment]
Yes, th'ats we have actually present in conference. Have to PR ecocode-common if i havent already did it. Will do next..

**Comment by Silicoman** [comment]
This is done here 
[Pull Request to add new tag eco-design to DocType rule](https://github.com/green-code-initiative/ecoCode-common/pull/16)

**Comment by Silicoman** [comment]
@participants, @mdubois81  

I try to add a reference/validation to this doctype rule. The Kanban ticket is lacking info: only "CPU consumption"
https://github.com/orgs/green-code-initiative/projects/1/views/1?filterQuery=CRDOM203&pane=issue&itemId=22378285

**Is it a fact?**

I have checked differents infos... without being convinced.

Thanks for your help


> Quirks mode:  Quirks mode is a technique used by many web browsers for maintaining backward compatibility with web pages designed for old web browsers instead of strictly complying with W3C standards. In Quirks mode, the internet browser tries to interpret on ‘best-guess’, this associated with a general understanding of code that might be not well structured, non-standard, or ineffectively written implies your page is running without a type declaration
> Reference: https://www.geeksforgeeks.org/difference-between-standards-mode-and-quirks-mode/
---
> In addition, the lack of Doctype HTML, as well as the browser quirks mode, can lead to vulnerability flaws. The lack of this declaration, even in newer browsers, makes pages vulnerable to attacks such as RPO (Relative path Overwrite), which acts in the injection of style sheets.
> 
> Therefore, we should not state that the doctype is not mandatory. W3C itself guides its use. Therefore, the use of Doctype HTML is essential for any document. Therefore, its use is mandatory in view of good practices and also to guarantee the perfect functioning and security of the document.
> reference : https://www.copahost.com/blog/html-doctype/
---
> There is no performance gain to it as far as i know. However, using a DOCTYPE makes a browser layout the page in a standards-compliant (and a more consistent, but not totally) way across browsers. This is a "handsomeness" benefit rather than speed.
> Since web browsers are implemented with special-purpose HTML parsers, rather than general-purpose DTD-based parsers, they don't use DTDs and will never access them even if a URL is provided. The DOCTYPE is retained in HTML5 as a "mostly useless, but required" header only to trigger "standards mode" in common browsers.
> reference: ttps://stackoverflow.com/questions/9697117/is-a-webpage-loaded-rendered-faster-with-html-4-transitional-or-html-5-dtd

**Comment by dedece35** [comment]
TO DISCUSS INSIDE CORE-TEAM : ok to merge associated PR ? (only add ecocode tag to existing SonarQube rule "Web:DoctypePresenceCheck")

**Comment by utarwyn** [comment]
This is an interesting idea, especially since this rule is essential in HTML5. So the starting point is to know if Quirks mode (which is activated when the doctype is not defined) is more resource intensive than standard mode.

Although I don't know exactly how browser rendering engines work, I am also unconvinced by the direct link with ecodesign. Experts seem to say that the difference in performance is negligible. The main objective of the DOCTYPE is to tell the browser to support all standard features and not stick with old ones (this is also why the rule on the SonarQube side is typed "user-experience"). BUT it is entirely possible that some of these standard features will increase page performance.

If we type the rule as "eco-design", we risk getting a lot of feedback asking us why it is typed that way. And without a concrete article explaining that Quirks mode is more resource-intensive (supporting proof), it seems complicated to argue..

**I would be in favor of not typing it as "eco-design". For now.**
Until someone proves that quirks mode really increases CPU consumption :+1:

**Comment by dedece35** [comment]
@utarwyn ok thank you for analysis
I think we can close this issue and wait for future. it's ok for you @utarwyn, @jhertout, @glalloue ?
(I moved the Kanban ticket to "hardly implementable")

**Comment by utarwyn** [comment]
After several tests, research, and given my comment https://github.com/green-code-initiative/ecoCode/issues/103#issuecomment-1751129818 this rule doesn't seem to be eco-design as it stands. So I propose to close this ticket.
