### ISSUE TITLE
[EC34] [PHP] raises issues on try-catch blocks without the finally clause

### ISSUE THREAD

**Issue by jycr** [green-code-initiative/ecoCode#173]
From @ganncamp (see: https://community.sonarsource.com/t/new-plugin-ecocode-requesting-inclusion-in-sonarqube-marketplace/85398/15):

> ecocode-php:EC34’s title is “Avoid using try-catch-finally”, but it raises issues on try-catch blocks without the finally clause. The code sample clears it up, but it seems the rule is really “Avoid using try-catch” or perhaps “Avoid using try-catch and try-catch-finally”?
>
> Ditto Python.

**Comment by dedece35** [comment]
Hi @jycr, (@glalloue, @mdubois81 , @jules-delecour-dav)

after investigation, for me this rule `EC34` is not valid rule because : 
- the issue description isn't accurate
- the rule only checks existence of `try` statement and then launch an issue
- I think this rule is applicable only for some cases (to be identified) : for example, use a test of existence or not of a file (or directory) instead of using a try catch based on `FileNotFoundException`

by the other hand, this rule is not present in 4th edition of 115 rules (see `RULES.md`).

to conclude, for me, this rule has to be refactored to do real good things.

**Comment by jycr** [comment]
If everyone agrees that the rule is currently not appropriate, why not just delete it?
We can work on it later (inspired by what has been developed by looking at the Git history).

**Comment by dedece35** [comment]
Hi @jycr,
the error message was modifier in 1.2.0 version to "Avoid using try-catch" instead of "Avoid using try-catch-finally" as asked for.
this rule is only implemented for PHP and Python plugin.

TO DISCUSS IN CORE TEAM : 
- do we keep this rule ? and make Java implementation also ?
- do we delete this rule ?

**Comment by glalloue** [comment]
OK to delete this rule (seen with Julien, Maxime, David)

**Comment by dedece35** [comment]
check TODOs on https://github.com/green-code-initiative/ecoCode/pull/128

**Comment by dedece35** [comment]
close because the work is done in #128
