### ISSUE TITLE
Unable to access to release analyze on SonarCloud

### ISSUE THREAD

**Issue by jycr** [green-code-initiative/ecoCode#207]
Release (git tag) is not currently analyzed by SonarCloud:
https://sonarcloud.io/project/overview?id=green-code-initiative_ecoCode

**Comment by dedece35** [comment]
Hi @jycr 
all repositories have been updated with the correction : 
- ecoCode : correction + test in 1.3.1 release (https://sonarcloud.io/summary/new_code?id=green-code-initiative_ecoCode&branch=refs%2Ftags%2F1.3.1)
- ecoCode-ios
- ecoCode-android
- ecoCode-javascript
- ecoCode-html

it's ok for you ? if ok, I will close this issue.
(I couldn't use a PR for this modification because I had to create a tag and a release to check if ok)

**Comment by jycr** [comment]
I understand why I didn't see release version in activity on main branch:

<img width="828" alt="image" src="https://github.com/green-code-initiative/ecoCode/assets/51145/b00cc8cf-4714-4005-9fd1-23c1539a0dd4">

-> because tags are made on ephemeral branches, and not on main branch.

**Comment by dedece35** [comment]
Hi @jycr,
the release process is done with maven plugin `release` which create this branch :p
