### ISSUE TITLE
Plugin Maven Dependency

### ISSUE THREAD

**Issue by milindbangar79** [green-code-initiative/ecoCode#227]
Hi,

1. I cannot download the JAR artifacts from Release Page on Github. The current release suggest 1.4.0 , but not available on Maven Central . How to get it ?
2. And can you please confirm the version scheme for language specific plugins ? I see 0.0.2 as latest available on Maven Central 

Thanks
Milind

**Comment by dedece35** [comment]
Hi @milindbangar79,
thank you for issue.

You're rigth. 
We are working on splitting "rules specifications" from to be automatically deployed on maven central with good version : you can follow this work with PR https://github.com/green-code-initiative/ecoCode/pull/209
Currently, without this PR ended, we deploy manually this artifact on maven central each time we make a new release with a manual version management.

I think we have a problem since this new system has been integrated, thus since 1.3.1 version of plugins.

If you want plugins that are ok, please use 1.3.0 waiting for our correction.

(plop @jycr @utarwyn @glalloue )

**Comment by dedece35** [comment]
@milindbangar79 

I checked the problem and finally I don't see the real problem.

I downloaded the last JAR 1.4.0 on release page for Java plugin.
I added it to my local SonarQube and all is ok : SonarQube starts, I see all my rules on quality profile, launch an analysis on java-test-project and I see the analysis.

1. If you go to https://github.com/green-code-initiative/ecoCode/releases, on "Asset" part just above, you can download "ecocode-java-plugin-1.4.0.jar" file (with link [ecocode-java-plugin-1.4.0.jar](https://github.com/green-code-initiative/ecoCode/releases/download/1.4.0/ecocode-java-plugin-1.4.0.jar) )
if you unzip this file, you can see all rules files in it : 
example : 
```
...
  inflating: io/ecocode/rules/java/EC32.html  
  inflating: io/ecocode/rules/java/EC1.html  
  inflating: io/ecocode/rules/java/EC203.json  
  inflating: io/ecocode/rules/java/EC3.html  
  inflating: io/ecocode/rules/java/EC28.json  
...
```
these rules files are packaged in released JAR file from "ecocode-rules-specifications" module

2. like explained on my previous comment, actually the maven central deployment is made manually. And lats version is 0.0.3. We are working on it to automatize deployment with good version.


Could you give me more informations on what you want to do and your working context please ?

**Comment by milindbangar79** [comment]
Hi @dedece35 ,

We cannot download JARs or for that matter any artifacts in the company and rely on Maven Central for JAVA APIs. It's restricted.

I can do on my personal machine , but not on company desktop.

Hence, I had created the issue , as on Maven Central, I could not see V1.4.0 , which I can procure and carry put a PoC . 

Hope I was clear .

Thanks
Milind

**Comment by dedece35** [comment]
@milindbangar79,
ok I understand your need, now.

to use ecocode plugins in a restricted environment, you must use official SonarQube Marketplace : on your SonarQube instance, go to "Administration" part, and then "MarketPlace". Here you can search for "ecocode" and you will find different "ecocode" plugins (one per language). You can install them by this way. Several societies asked for this official way like you to install our plugins in their SonarQube instances.
Indeed, last version available in SonarQube Markeplace is 1.3.0.
Versions 1.3.1 and 1.4.0 are not in markeplace yet, because we have to submit them to MarketPlace moderation.
This will be done this month, I think, with the new release that will be made soon (1.4.1 or 1.5.0) for each language.

What you see on Maven Central is not plugins themselves but only a little part for real plugins. You can't use the "ecocode-rules-specifications" component directly.

Is it clear for you, now ?

**Comment by dedece35** [comment]
Hi @milindbangar79,
I close this issue because for me I give you an answer.
Re-open it if it's not clear.

**Comment by milindbangar79** [comment]
Hi David,

Thanks for the response and apologies for late response.
Regards
Milind
