### ISSUE TITLE
[EC4][Java] Rule is not applicable to Java

### ISSUE THREAD

**Issue by cyChop** [green-code-initiative/ecoCode#233]
**Describe the bug**
The rule "avoid global variables" is not applicable to Java.

The history: the first rules were inspired by web best practices, and transposed to other languages without analysis due to lack of time. This shows in the description of this rule, which shows JS.

Scope is not an issue in Java, and constants are a best practice for readability and memory optimization. EC4 _is not_ applicable to Java and should be removed.

**Comment by utarwyn** [comment]
I agree that this rule should be discussed, it seems not revelant in Java.
I would even say that this rule is not applicable in JavaScript, I do not see the gain in terms of performance/eco-design. It is a bad practice in general (for security reasons for example), variables should be scoped accordingly.

And I no longer see the rule in the latest version of best practices repo/book?

**Comment by cvgaviao** [comment]
Is it is not applicable for Java at all. and I almost freak out after I saw that the number of issues of our project have increased from 10 to 310 from one day to another because of it, plus EC2 and EC75 :)

**Comment by dedece35** [comment]
Hi @cyChop, @utarwyn, @diyfr, @cvgaviao,
I agree with you on EC4. Please feel free to contribute with a PR to make this rule deprecated for Java language. For this, please make followed tasks : 
- update RULES.md to update Java pictogram
- update CHANGELOG.md to explain deprecation
- delete Java rule implementation and tests on `ecocode` repository
- delete Java test implementation on `ecocode-java-test-project` repository

Regarding EC2 rule, sorry, I don't agree. Please check refactoring work in issue https://github.com/green-code-initiative/ecoCode/issues/216 and associated PR https://github.com/green-code-initiative/ecoCode/pull/222.
Unfortunately, this work is not released yet (see CHANGELOG.md) but soon.

Regarding EC75, sorry again, I don't agree. For me it has been a good practice since a long time. Maybe now, with JVM updates, this rule is deprecated. If it is, please could you give us documentation on this point, @cvgaviao, please ?

**Comment by diyfr** [comment]
Hello @dedece35,  you validate the test files said "COMPLIANT" with classic sonar rules to avoid conflict ?

**Comment by cyChop** [comment]
> But if you want to discuss about EC2 and EC75, please open a new issue for each, if you don't agree with my comments above. Thank you :p !

I think your mailbox trapped you, because I made an issue for each. I'll quote you on those issues and answer there. :)
