### ISSUE TITLE
[EC67] [Java] IncrementCheck irrelevant

### ISSUE THREAD

**Issue by arn-aud** [green-code-initiative/ecoCode#60]
The IncrementCheck seems irrelevant since the java compiler produces the same byte code in many cases.

1. write a class with a for-loop using i++ to increment the counter
2. duplicate the class and replace i++ with ++i
3. compile both classes
4. compare the generated bytecode
5. no differences found

**Comment by dedece35** [comment]
Hi @arn-aud,

thank you for your issue.
after checking, this isn't so simple.

Here are my screenshots from our java test-project named [`ecoCode-java-test-project`](https://github.com/green-code-initiative/ecoCode-java-test-project) : 
- first screenshot : java sources
- second screenshot : decompiled class files (from these java sources)

<img width="685" alt="sources-1" src="https://user-images.githubusercontent.com/12011401/230796100-344c3109-1caa-4988-9828-ce399af02fd5.png">
<img width="685" alt="sources-2" src="https://user-images.githubusercontent.com/12011401/230796058-c603761c-b129-43ce-b925-d729decc736d.png">
<img width="562" alt="Capture d’écran 2023-04-09 à 22 51 51" src="https://user-images.githubusercontent.com/12011401/230796076-bfe8dc40-0f25-4902-82ee-b4343e560aaa.png">


What we can observe : 
- `foo1` method : no difference
- `foo11` method : no difference
- `foo2` method : no difference
- `foo22` method : Here is a difference ==> indeed, compilation transformed `++counter` to `counter++`, maybe because of no usage of `counter` variable after increment (contrary to the case of `foo11` in which `counter` variable is returned)
- `foo3` method : Here is a difference ==> usage of `+=`operator instead of `=` operator with source variable
- `foo4` method : no difference
- `foo50` method (first NEW method to follow your recommended test) : no difference
- `foo51` method (second NEW method to follow your recommended test) : Here is a difference ==> `++i` replaced with `i++`. For me, this is the same use case than `foo22`, because in this `for` loop, `i` varibale is incremented in a last instruction and there is no direct use of it, like `foo22`

To conclude, I think, the optimization is smarter than we thought and for me, the rule is relevant in some cases. But, as we can see, the default behaviour for compiler optimization is to put `++` operator as suffix.

**Comment by dedece35** [comment]
TO DISCUSS INSIDE CORE-TEAM : opinion ? to keep or not ? for me, to keep.

**Comment by glalloue** [comment]
@dedece35 demonstration show that argument was not right bu do not show that the rule is efficient or not.
we can close this issue , but we need to keep the discussion to understand if the rule is right or not

(seen with @dedece35 and @jhertout )
